using System.Diagnostics;
using SpeedcubingTrainer.Core.Cube;

namespace SpeedcubingTrainer.Core.Solver;

public enum SolveStatus
{
    Found,
    TimedOut,
    NotFound,
    Invalid,
}

/// <param name="MaxLength">Longest solution that is acceptable at all.</param>
/// <param name="TargetLength">The search stops as soon as it finds a solution this short; until then it keeps improving.</param>
/// <param name="TimeBudget">Wall-clock budget; the best solution found so far is returned when it runs out.</param>
/// <param name="MaxPhase1Depth">Deepest phase 1 search; 12 always suffices.</param>
public sealed record SolverOptions(int MaxLength = 24, int TargetLength = 21, TimeSpan? TimeBudget = null, int MaxPhase1Depth = 12)
{
    public static readonly SolverOptions Default = new();

    public TimeSpan Budget => TimeBudget ?? TimeSpan.FromSeconds(2);
}

public sealed record SolveResult(SolveStatus Status, Algorithm? Solution, TimeSpan Elapsed, long Nodes)
{
    public bool IsFound => Status == SolveStatus.Found;
}

/// <summary>
/// Kociemba's two-phase algorithm without symmetry reduction: phase 1 brings the cube into the
/// subgroup generated by U, D, R2, F2, L2, B2 (orientations solved, slice edges in the slice); phase 2
/// solves it inside that subgroup. Both phases are IDA* searches over coordinate triples.
/// </summary>
public sealed class TwoPhaseSolver(SolverTables tables)
{
    private static readonly int[] Phase2MoveIndex = BuildPhase2Index();

    public SolveResult Solve(CubieCube cube, SolverOptions? options = null, CancellationToken cancellationToken = default)
    {
        options ??= SolverOptions.Default;
        var stopwatch = Stopwatch.StartNew();
        if (cube.Validate() != CubeValidity.Valid)
        {
            return new SolveResult(SolveStatus.Invalid, null, stopwatch.Elapsed, 0);
        }
        var search = new Search(tables, cube, options, cancellationToken);
        var status = search.Run(out var solution);
        return new SolveResult(status, solution, stopwatch.Elapsed, search.Nodes);
    }

    public SolveResult Solve(CubeState state, SolverOptions? options = null, CancellationToken cancellationToken = default)
    {
        CubieCube cube;
        try
        {
            cube = state.ToCubieCube();
        }
        catch (InvalidCubeException)
        {
            return new SolveResult(SolveStatus.Invalid, null, TimeSpan.Zero, 0);
        }
        return Solve(cube, options, cancellationToken);
    }

    private static int[] BuildPhase2Index()
    {
        var index = new int[SolverTables.Phase1MoveCount];
        Array.Fill(index, -1);
        for (var m = 0; m < SolverTables.Phase2Moves.Length; m++)
        {
            index[SolverTables.Phase2Moves[m]] = m;
        }
        return index;
    }

    private sealed class Search(SolverTables tables, CubieCube start, SolverOptions options, CancellationToken cancellationToken)
    {
        private readonly int[] _phase1 = new int[options.MaxPhase1Depth + 1];
        private readonly int[] _phase2 = new int[19];
        private readonly Stopwatch _stopwatch = Stopwatch.StartNew();
        private readonly CubieCube _scratch = new();
        private int _phase1Length;
        private bool _aborted;
        private Move[]? _best;

        public long Nodes { get; private set; }

        private int BestLength => _best?.Length ?? options.MaxLength + 1;

        /// <summary>
        /// Deepens phase 1 one move at a time. Every phase 1 solution gets a phase 2 search bounded by the best
        /// total found so far, and the search ends once a solution no longer than the target length exists.
        /// Phase 1 returns true only when the search must stop (time budget or cancellation).
        /// </summary>
        public SolveStatus Run(out Algorithm? solution)
        {
            var twist = Coordinates.GetTwist(start);
            var flip = Coordinates.GetFlip(start);
            var slice = Coordinates.GetSlice(start);

            // Each phase 1 depth is searched completely before the target is checked, so short
            // scrambles get short solutions even when the first phase 1 solution leads to a long phase 2.
            for (var depth = 0; depth <= options.MaxPhase1Depth && depth < BestLength; depth++)
            {
                Phase1(twist, flip, slice, depth, -1, 0);
                if (_aborted || BestLength <= options.TargetLength)
                {
                    break;
                }
            }

            if (_best is not null)
            {
                solution = new Algorithm(_best);
                return SolveStatus.Found;
            }
            solution = null;
            return _aborted ? SolveStatus.TimedOut : SolveStatus.NotFound;
        }

        private bool Tick()
        {
            if ((++Nodes & 1023) == 0 && (_stopwatch.Elapsed > options.Budget || cancellationToken.IsCancellationRequested))
            {
                _aborted = true;
            }
            return !_aborted;
        }

        private bool Phase1(int twist, int flip, int slice, int remaining, int lastFace, int index)
        {
            if (!Tick())
            {
                return false;
            }
            if (remaining == 0)
            {
                if (twist != 0 || flip != 0 || slice != 0)
                {
                    return false;
                }
                // A phase 1 solution ending in a phase 2 move was already covered at a shorter depth.
                if (index > 0 && Phase2MoveIndex[_phase1[index - 1]] >= 0)
                {
                    return false;
                }
                _phase1Length = index;
                return Phase2Entry(lastFace);
            }

            var heuristic = Math.Max(
                tables.TwistSlicePrune[twist * Coordinates.SliceCount + slice],
                tables.FlipSlicePrune[flip * Coordinates.SliceCount + slice]);
            if (heuristic > remaining)
            {
                return false;
            }

            for (var m = 0; m < SolverTables.Phase1MoveCount; m++)
            {
                var face = m / 3;
                if (!AllowedAfter(face, lastFace))
                {
                    continue;
                }
                _phase1[index] = m;
                var nextTwist = tables.TwistMove[twist * SolverTables.Phase1MoveCount + m];
                var nextFlip = tables.FlipMove[flip * SolverTables.Phase1MoveCount + m];
                var nextSlice = tables.SliceMove[slice * SolverTables.Phase1MoveCount + m];
                if (Phase1(nextTwist, nextFlip, nextSlice, remaining - 1, face, index + 1))
                {
                    return true;
                }
                if (_aborted)
                {
                    return false;
                }
            }
            return false;
        }

        private bool Phase2Entry(int lastFace)
        {
            _scratch.CopyFrom(start);
            for (var i = 0; i < _phase1Length; i++)
            {
                var m = _phase1[i];
                var moveCube = CubieCube.MoveCubes[m / 3];
                for (var t = 0; t <= m % 3; t++)
                {
                    _scratch.Multiply(moveCube);
                }
            }
            var corners = Coordinates.GetCornerPerm(_scratch);
            var edges = Coordinates.GetUdEdgePerm(_scratch);
            var slice = Coordinates.GetSlicePerm(_scratch);

            // Only look for a strict improvement on the best complete solution so far.
            var maxDepth = Math.Min(18, BestLength - 1 - _phase1Length);
            for (var depth = 0; depth <= maxDepth; depth++)
            {
                if (Phase2(corners, edges, slice, depth, lastFace, 0))
                {
                    RecordSolution(depth);
                    return false;
                }
                if (_aborted)
                {
                    return false;
                }
            }
            return false;
        }

        private bool Phase2(int corners, int edges, int slice, int remaining, int lastFace, int index)
        {
            if (!Tick())
            {
                return false;
            }
            if (remaining == 0)
            {
                return corners == 0 && edges == 0 && slice == 0;
            }

            var heuristic = Math.Max(
                tables.CornerSlicePrune[corners * Coordinates.SlicePermCount + slice],
                tables.EdgeSlicePrune[edges * Coordinates.SlicePermCount + slice]);
            if (heuristic > remaining)
            {
                return false;
            }

            for (var m = 0; m < SolverTables.Phase2MoveCount; m++)
            {
                var face = SolverTables.Phase2Moves[m] / 3;
                if (!AllowedAfter(face, lastFace))
                {
                    continue;
                }
                _phase2[index] = m;
                var nextCorners = tables.CornerPermMove[corners * SolverTables.Phase2MoveCount + m];
                var nextEdges = tables.UdEdgePermMove[edges * SolverTables.Phase2MoveCount + m];
                var nextSlice = tables.SlicePermMove[slice * SolverTables.Phase2MoveCount + m];
                if (Phase2(nextCorners, nextEdges, nextSlice, remaining - 1, face, index + 1))
                {
                    return true;
                }
                if (_aborted)
                {
                    return false;
                }
            }
            return false;
        }

        /// <summary>Never turn the same face twice in a row; turn opposite faces only in a fixed order (U before D, R before L, F before B).</summary>
        private static bool AllowedAfter(int face, int lastFace) =>
            lastFace < 0 || (face != lastFace && !(face % 3 == lastFace % 3 && face < lastFace));

        private void RecordSolution(int phase2Length)
        {
            var moves = new Move[_phase1Length + phase2Length];
            for (var i = 0; i < _phase1Length; i++)
            {
                moves[i] = new Move((MoveTarget)(_phase1[i] / 3), (Turn)(_phase1[i] % 3 + 1));
            }
            for (var i = 0; i < phase2Length; i++)
            {
                var m = SolverTables.Phase2Moves[_phase2[i]];
                moves[_phase1Length + i] = new Move((MoveTarget)(m / 3), (Turn)(m % 3 + 1));
            }
            _best = moves;
        }
    }
}
